### ISSUE TITLE
Dokumentation für Datenformate beim Dateiimport

### ISSUE THREAD

**Issue by cecile-node** [node-energy/node-energy-pre-commit-hooks#4]
Wenn ich als Kunde einen Datenimport mache, möchte ich eine gute Dokumentation der unterstützten Dateiformate, damit ich möglichst wenig Fehler mache und mich sicher geführt fühle

AC

- [ ] Erweiterung der Dokumentation in Confluence auf alle im Code aufgeführten unterstützten Dateiformate: https://node-energy.atlassian.net/wiki/spaces/~376074181/pages/228524033/Unterst+tze+Datenformate

**Comment by cecile-node** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wind-PV-Voll-Hilfsfunktionen-624474522e648a00107f4fed/issues/node-energy/node-energy-pre-commit-hooks/4?planning-poker) with ZenHub @raytracer @Pfirsichriegel

**Comment by cecile-node** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wind-PV-Voll-Hilfsfunktionen-624474522e648a00107f4fed/issues/node-energy/node-energy-pre-commit-hooks/4?planning-poker) with ZenHub @AndreasKosyrev

**Comment by jayeff** [comment]
closing old issues (probably landed in wrong repo)
