### ISSUE TITLE
Seriennummern-Update für Dritte im Windpark

### ISSUE THREAD

**Issue by cecile-node** [node-energy/node-energy-pre-commit-hooks#7]
Als Onboarding-Mitglied möchte ich, dass die WEA-Zählernummer und die Untermesssysteme automatisch auf die duplizierten Projekte übertragen werden, wenn es eine Änderung gibt.

AC:

- [ ] die Zählernummer eines führenden Zählers soll auf die abhängigen Zähler übertragen werden
- [ ] es gibt ein initiales Update
- [ ] immer wenn sich etwas ändert sollen automatisch die anderen Systeme geupdatet werden

INFO:
es wird kein Unterschied gemacht zwischen kalibrierten und nicht kalibrierten Zählern
es gibt "führende Zähler": die Zähler des Kunden und "abhängige Zähler": vorhandene Daten auf einem führenden Zähler sollen nie überschrieben werden
Mess- und Marktlokationen: es werden alle Projekte geupdatet, die noch keine Daten haben
Führend sind:
Mess und Marktlokationen
Zähler von Anlagen, für die in diesem Projekt Pflichten erfüllt werden****

**Comment by jayeff** [comment]
closing old issues (probably landed in wrong repo)
